name: Build and test webR

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build Nix package
        run: nix build --print-build-logs